name: 'Detekt PR Reporter'
description: 'Posts detekt report as a comment on pull requests'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: false
  report_path:
    description: 'Path to the detekt markdown report file'
    required: true
  
runs:
  using: 'node16'
  main: 'dist/index.js'
