name: 'Detekt Markdown Report'
description: 'Publishes Detekt markdown report to pull request'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  report_path:
    description: 'Path to the Detekt markdown report file'
    required: true
runs:
  using: 'node16'
  main: 'src/main.js'
